"""add search indexes

Revision ID: 11d611888606
Revises: 90b97f71e23f
Create Date: 2026-10-08 14:42:07.928566

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "11d611888606"
down_revision: str | Sequence[str] | None = "90b97f71e23f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
